import {
  Accountable,
  Ajeet,
  Arpit,
  Ayush,
  Commitment,
  Companies1,
  Companies2,
  Companies3,
  Companies4,
  Companies5,
  Companies6,
  Delivery,
  Dev,
  Hint,
  Lakshyaveer,
  Nirvika,
  OfficeIndia,
  OfficeUs,
  Rashid,
  Rishabh,
  Ritu,
  Sanyam,
  Testimonial1,
  Testimonial2,
  Testimonial3,
  Testimonial4,
  Testimonial5,
  Testimonial6,
  Vipul,
  Yashasvi,
} from "../assets";
import Icons from "./Icons";

export const Designation = [
  { label: "Front End Developer", value: "front_end_developer" },
  { label: "Back End Developer", value: "back_end_developer" },
  { label: "Full Stack Developer", value: "full_stack_developer" },
  {
    label: "Associate Software Engineer",
    value: "associate_software_engineer",
  },
  { label: "Software Engineer", value: "software_engineer" },
  { label: "Senior Software Engineer", value: "senior_software_engineer" },
  { label: "Tech Lead", value: "tech_lead" },
  { label: "Engineering Manager", value: "engineering_manager" },
  { label: "QA Engineer", value: "qa_engineer" },
  { label: "QA Automation Engineer", value: "qa_automation_engineer" },
  { label: "QA Analyst", value: "qa_analyst" },
  { label: "UI/UX Designer", value: "ui_ux_designer" },
  { label: "Product Designer", value: "product_designer" },
  { label: "Graphic Designer", value: "graphic_designer" },
  { label: "Business Analyst", value: "business_analyst" },
  { label: "Product Manager", value: "product_manager" },
  { label: "Project Manager", value: "project_manager" },
  { label: "Scrum Master", value: "scrum_master" },
  {
    label: "Business Development Executive",
    value: "business_development_executive",
  },
  {
    label: "Business Development Manager",
    value: "business_development_manager",
  },
  { label: "DevOps Engineer", value: "devops_engineer" },
  { label: "Cloud Engineer", value: "cloud_engineer" },
  { label: "Site Reliability Engineer", value: "site_reliability_engineer" },
  { label: "Cybersecurity Engineer", value: "cybersecurity_engineer" },
  { label: "Data Engineer", value: "data_engineer" },
  { label: "Data Scientist", value: "data_scientist" },
  { label: "AI/ML Engineer", value: "ai_ml_engineer" },
  { label: "Marketing Manager", value: "marketing_manager" },
  { label: "SEO Specialist", value: "seo_specialist" },
  { label: "Content Marketing Manager", value: "content_marketing_manager" },
  { label: "Sales Manager", value: "sales_manager" },
  { label: "Customer Success Manager", value: "customer_success_manager" },
  { label: "Human Resources Manager", value: "human_resources_manager" },
  {
    label: "Talent Acquisition Specialist",
    value: "talent_acquisition_specialist",
  },
  { label: "Finance Manager", value: "finance_manager" },
  { label: "Accountant", value: "accountant" },
  { label: "Legal Advisor", value: "legal_advisor" },
  { label: "Technical Support Engineer", value: "technical_support_engineer" },
  { label: "System Administrator", value: "system_administrator" },
  { label: "Network Engineer", value: "network_engineer" },
  { label: "Embedded Systems Engineer", value: "embedded_systems_engineer" },
  { label: "Game Developer", value: "game_developer" },
  { label: "AR/VR Developer", value: "ar_vr_developer" },
  { label: "Blockchain Developer", value: "blockchain_developer" },
];

export const Difficulty = [
  { label: "Fresher", value: "FRESHER" },
  { label: "Easy", value: "EASY" },
  { label: "Medium", value: "MEDIUM" },
  { label: "Hard", value: "HARD" },
];

export const QuestionDifficultyCoins: { [key: string]: number[] } = {
  EASY: [0, 5, 10, 15, 20, 25, 30],
  MEDIUM: [35, 40, 45, 50, 55, 60],
  HARD: [65, 70, 75, 80, 85, 90, 95, 100],
};

export const ProctorOptions = [
  { id: "TAB", name: "Tab Switch" },
  { id: "COPY", name: "Copy" },
  { id: "PASTE", name: "Paste" },
  { id: "CELLPHONE", name: "Cell Phone" },
  { id: "PROHIBITEDOBJECT", name: "Prohibited Object" },
  { id: "FACENOTVISIBLE", name: "Face Visibility" },
  { id: "ANOTHERPERSON", name: "Multiple Face" },
  { id: "LOOKINGAWAY", name: "Looking Away" },
];

export const ProctorTestOptions = [
  { id: "TAB", name: "Tab Switch" },
  { id: "COPY", name: "Copy" },
  { id: "PASTE", name: "Paste" },
  { id: "AUDIO", name: "Audio" },
  { id: "CELLPHONE", name: "Cell Phone" },
  { id: "PROHIBITEDOBJECT", name: "Prohibited Object" },
  { id: "FACENOTVISIBLE", name: "Face Visibility" },
  { id: "ANOTHERPERSON", name: "Multiple Face" },
  { id: "LOOKINGAWAY", name: "Looking Away" },
];

export const OrganizationType = [
  { label: "Organization", value: "ORGANIZATION" },
  { label: "University", value: "UNIVERSITY" },
];

export const JobType = [
  { value: "FULLTIME", label: "Full-Time" },
  { value: "PARTTIME", label: "Part-Time" },
  { value: "INTERNSHIP", label: "Internship" },
  { value: "CONTRACT", label: "Contract" },
  { value: "FREELANCE", label: "Freelance" },
  { value: "VOLUNTEER", label: "Volunteer" },
  { value: "TRAINING", label: "Training" },
  { value: "OTHER", label: "Other" },
];

export const DriveStatus = [
  { label: "Scheduled", value: "SCHEDULED" },
  { label: "Ongoing", value: "ONGOING" },
  { label: "Completed", value: "COMPLETED" },
  { label: "Draft", value: "DRAFT" },
];

export const DriveType = [
  { label: "Public", value: "PUBLIC" },
  { label: "Private", value: "PRIVATE" },
  { label: "Pool", value: "POOL" },
];

export const JobLocationType = [
  { label: "Remote", value: "REMOTE" },
  { label: "Onsite", value: "ONSITE" },
  { label: "Hybrid", value: "HYBRID" },
];

export const VenueType = [
  { label: "SkillBrew", value: "SKILLBREW" },
  { label: "Online", value: "ONLINE" },
  { label: "Offline", value: "OFFLINE" },
];

export const RoleType = [
  { value: "FRONTEND_DEVELOPER", label: "Frontend Developer" },
  { value: "BACKEND_DEVELOPER", label: "Backend Developer" },
  { value: "FULLSTACK_DEVELOPER", label: "Fullstack Developer" },
  { value: "WEB_DEVELOPER", label: "Web Developer" },
  { value: "MOBILE_APP_DEVELOPER", label: "Mobile App Developer" },
  { value: "SOFTWARE_ENGINEER", label: "Software Engineer" },
  { value: "SDE_1", label: "SDE I" },
  { value: "SDE_2", label: "SDE II" },
  { value: "SDE_3", label: "SDE III" },
  { value: "DATA_SCIENTIST", label: "Data Scientist" },
  { value: "DATA_ANALYST", label: "Data Analyst" },
  { value: "MACHINE_LEARNING_ENGINEER", label: "Machine Learning Engineer" },
  { value: "AI_ENGINEER", label: "AI Engineer" },
  { value: "DEVOPS_ENGINEER", label: "DevOps Engineer" },
  { value: "QA_ENGINEER", label: "QA Engineer" },
  { value: "TEST_ENGINEER", label: "Test Engineer" },
  { value: "CLOUD_ENGINEER", label: "Cloud Engineer" },
  { value: "BLOCKCHAIN_DEVELOPER", label: "Blockchain Developer" },
  { value: "DATABASE_ADMINISTRATOR", label: "Database Administrator" },
  { value: "SYSTEM_ADMINISTRATOR", label: "System Administrator" },
  { value: "SECURITY_ENGINEER", label: "Security Engineer" },
  { value: "NETWORK_ENGINEER", label: "Network Engineer" },
  { value: "RESEARCH_ENGINEER", label: "Research Engineer" },
  { value: "TECHNICAL_WRITER", label: "Technical Writer" },
  { value: "UI_UX_DESIGNER", label: "UI/UX Designer" },
  { value: "PRODUCT_DESIGNER", label: "Product Designer" },
  { value: "GRAPHIC_DESIGNER", label: "Graphic Designer" },
  { value: "TECH_LEAD", label: "Tech Lead" },
  { value: "ENGINEERING_MANAGER", label: "Engineering Manager" },
  { value: "CTO", label: "CTO" },
  { value: "PROJECT_MANAGER", label: "Project Manager" },
  { value: "PRODUCT_MANAGER", label: "Product Manager" },
  { value: "HR_MANAGER", label: "HR Manager" },
  { value: "RECRUITER", label: "Recruiter" },
  { value: "BUSINESS_ANALYST", label: "Business Analyst" },
  { value: "MARKETING_MANAGER", label: "Marketing Manager" },
  { value: "DIGITAL_MARKETER", label: "Digital Marketer" },
  { value: "CONTENT_WRITER", label: "Content Writer" },
  { value: "COPYWRITER", label: "Copywriter" },
  { value: "CUSTOMER_SUPPORT_EXECUTIVE", label: "Customer Support Executive" },
  { value: "OPERATIONS_MANAGER", label: "Operations Manager" },
  { value: "FINANCE_MANAGER", label: "Finance Manager" },
  { value: "SALES_EXECUTIVE", label: "Sales Executive" },
  { value: "ACCOUNT_MANAGER", label: "Account Manager" },
  { value: "LEGAL_ADVISOR", label: "Legal Advisor" },
  { value: "INTERN", label: "Intern" },
];

export const IndustryType = [
  { value: "ANALYTICS", label: "Analytics" },
  { value: "IT", label: "Information Technology" },
  { value: "FINANCE", label: "Finance" },
  { value: "FINANCE_BANKING", label: "Banking" },
  { value: "FINANCE_INSURANCE", label: "Insurance" },
  { value: "FINANCE_INVESTMENT", label: "Investment" },
  { value: "FINANCE_FINTECH", label: "Fintech" },
  { value: "HEALTHCARE", label: "Healthcare" },
  { value: "HEALTHCARE_HOSPITALS", label: "Hospitals" },
  { value: "HEALTHCARE_BIOTECH", label: "Biotechnology" },
  { value: "HEALTHCARE_PHARMACEUTICALS", label: "Pharmaceuticals" },
  { value: "HEALTHCARE_MEDICAL_DEVICES", label: "Medical Devices" },
  { value: "MANUFACTURING", label: "Manufacturing" },
  { value: "MANUFACTURING_AUTOMOTIVE", label: "Automotive Manufacturing" },
  {
    value: "MANUFACTURING_HEAVY_EQUIPMENT",
    label: "Heavy Equipment Manufacturing",
  },
  { value: "MANUFACTURING_ELECTRONICS", label: "Electronics Manufacturing" },
  { value: "RETAIL", label: "Retail" },
  { value: "RETAIL_ECOMMERCE", label: "E-commerce" },
  { value: "RETAIL_FASHION", label: "Fashion Retail" },
  { value: "RETAIL_FOOD", label: "Food Retail" },
  { value: "RETAIL_GROCERY", label: "Grocery Retail" },
  { value: "EDUCATION", label: "Education" },
  { value: "EDUCATION_Higher_EDU", label: "Higher Education" },
  { value: "EDUCATION_TRAINING", label: "Corporate Training" },
  { value: "EDUCATION_EDTECH", label: "EdTech" },
  { value: "MEDIA", label: "Media" },
  { value: "MEDIA_BROADCASTING", label: "Broadcasting" },
  { value: "MEDIA_PUBLISHING", label: "Publishing" },
  { value: "MEDIA_ADVERTISING", label: "Advertising" },
  { value: "REAL_ESTATE", label: "Real Estate" },
  { value: "REAL_ESTATE_COMMERCIAL", label: "Commercial Real Estate" },
  { value: "REAL_ESTATE_RESIDENTIAL", label: "Residential Real Estate" },
  { value: "TRAVEL", label: "Travel & Tourism" },
  { value: "TRAVEL_AIRLINES", label: "Airlines" },
  { value: "TRAVEL_HOTELS", label: "Hotels & Lodging" },
  { value: "TRAVEL_TOURISM", label: "Tourism Services" },
  { value: "LOGISTICS", label: "Logistics" },
  { value: "LOGISTICS_SUPPLY_CHAIN", label: "Supply Chain Management" },
  { value: "LOGISTICS_SHIPPING", label: "Shipping & Freight" },
  { value: "LOGISTICS_WAREHOUSING", label: "Warehousing & Distribution" },
  { value: "ENERGY", label: "Energy" },
  { value: "ENERGY_RENEWABLE", label: "Renewable Energy" },
  { value: "ENERGY_OIL_GAS", label: "Oil & Gas" },
  { value: "ENERGY_UTILITY", label: "Utilities" },
  { value: "AUTOMOTIVE", label: "Automotive" },
  { value: "AUTOMOTIVE_MANUFACTURING", label: "Automotive Manufacturing" },
  { value: "AUTOMOTIVE_SALES", label: "Automotive Sales" },
  { value: "CONSTRUCTION", label: "Construction" },
  { value: "CONSTRUCTION_COMMERCIAL", label: "Commercial Construction" },
  { value: "CONSTRUCTION_RESIDENTIAL", label: "Residential Construction" },
  { value: "AEROSPACE", label: "Aerospace" },
  { value: "AEROSPACE_DEFENSE", label: "Aerospace & Defense" },
  { value: "AEROSPACE_COMMERCIAL", label: "Commercial Aviation" },
  { value: "AGRICULTURE", label: "Agriculture" },
  { value: "AGRICULTURE_CROP_PRODUCTION", label: "Crop Production" },
  { value: "AGRICULTURE_LIVESTOCK", label: "Livestock Farming" },
  { value: "AGRICULTURE_AGTECH", label: "Agricultural Technology" },
  { value: "TELECOMMUNICATIONS", label: "Telecommunications" },
  { value: "TELECOMMUNICATIONS_MOBILE", label: "Mobile Services" },
  { value: "TELECOMMUNICATIONS_BROADBAND", label: "Broadband Services" },
  { value: "LEGAL", label: "Legal Services" },
  { value: "LEGAL_LAW_FIRMS", label: "Law Firms" },
  { value: "LEGAL_IN_HOUSE", label: "In-House Legal Departments" },
  { value: "GOVERNMENT", label: "Government" },
  { value: "GOVERNMENT_PUBLIC_SERVICES", label: "Public Services" },
  { value: "GOVERNMENT_MUNICIPAL", label: "Municipal Government" },
  { value: "GOVERNMENT_FEDERAL", label: "Federal Government" },
  { value: "NONPROFIT", label: "Nonprofit" },
  { value: "NONPROFIT_NGOs", label: "Non-Governmental Organizations (NGOs)" },
  { value: "NONPROFIT_CHARITIES", label: "Charities" },
  { value: "ENTERTAINMENT", label: "Entertainment" },
  { value: "ENTERTAINMENT_FILM", label: "Film Industry" },
  { value: "ENTERTAINMENT_MUSIC", label: "Music Industry" },
  { value: "ENTERTAINMENT_LIVE_EVENTS", label: "Live Events" },
  { value: "SPORTS", label: "Sports" },
  { value: "SPORTS_TEAMS", label: "Sports Teams" },
  { value: "SPORTS_EQUIPMENT", label: "Sports Equipment Manufacturing" },
  { value: "SPORTS_MANAGEMENT", label: "Sports Management & Agencies" },
];

export const DepartmentType = [
  { value: "HR", label: "HR" },
  { value: "IT", label: "IT" },
  { value: "FINANCE", label: "Finance" },
  { value: "MARKETING", label: "Marketing" },
  { value: "SALES", label: "Sales" },
  { value: "OPERATIONS", label: "Operations" },
  { value: "RESEARCH", label: "Research" },
  { value: "DESIGN", label: "Design" },
  { value: "CUSTOMERSUPPORT", label: "Customer Support" },
  { value: "LEGAL", label: "Legal" },
  { value: "ENGINEERING", label: "Engineering" },
  { value: "PRODUCT", label: "Product" },
  { value: "SUPPLY_CHAIN", label: "Supply Chain" },
  { value: "OTHER", label: "Other" },
];

export const MinimumQualificationType = [
  { value: "10TH", label: "10th" },
  { value: "12TH", label: "12th" },
  { value: "DIPLOMA", label: "Diploma" },
  { value: "GRADUATE", label: "Graduate" },
  { value: "POSTGRADUATE", label: "Postgraduate" },
  { value: "DOCTORATE", label: "Doctorate" },
];

export const GenderForType = [
  { value: "EVERYONE", label: "Everyone" },
  { value: "MALE", label: "Male" },
  { value: "FEMALE", label: "Female" },
  { value: "OTHER", label: "Other" },
];

export const DriveInvitationStatus = [
  { label: "Accepted", value: "ACCEPTED" },
  { label: "Rejected", value: "REJECTED" },
  { label: "Pending", value: "PENDING" },
];

export const DriveInvitee = [
  { label: "User", value: "USER" },
  { label: "University", value: "UNIVERSITY" },
  { label: "Organization", value: "ORGANIZATION" },
];

export const DriveStage = [
  { label: "Preplacement Talk", value: "PREPLACEMENT" },
  { label: "Resume Shortlisting", value: "RESUME" },
  { label: "Assessment", value: "ASSESSMENT" },
  { label: "AI Interview", value: "AIINTERVIEW" },
  { label: "Interview", value: "INTERVIEW" },
  { label: "GD", value: "GD" },
  { label: "Other", value: "OTHER" },
];

export const RoundVerdict = [
  { label: "All", value: "" },
  { label: "Selected", value: "SELECTED" },
  { label: "Rejected", value: "REJECTED" },
  { label: "Next Round", value: "NEXROUND" },
  { label: "On Hold", value: "ONHOLD" },
  // { label: "Reschedule", value: "RESCHEDULE" },
  { label: "Pending", value: "PENDING" },
  // { label: "Disqualified", value: "DISQUALIFIED" },
];

export const ApplicantStatusOption = [
  {
    label: "Hired",
    value: "HIRED",
    class: "success-status",
    icon: Icons?.selected,
  },
  {
    label: "Passed",
    value: "PASSED",
    class: "primary-status",
    icon: Icons?.nextRound,
  },
  {
    label: "On Hold",
    value: "ONHOLD",
    class: "warning-status",
    icon: Icons?.onHold,
  },
  {
    label: "Rejected",
    value: "REJECTED",
    class: "danger-status",
    icon: Icons?.rejected,
  },
];

export const DriveRoundPlatform = [
  { label: "SKB", value: "SKB" },
  { label: "Meet", value: "MEET" },
  { label: "Zoom", value: "ZOOM" },
  { label: "Other", value: "OTHER" },
];

export const NotificationStatus = [
  { label: "Read", value: "READ" },
  { label: "Unread", value: "UNREAD" },
];

export const NotificationRecipientType = [
  { label: "User", value: "USER" },
  { label: "Organization", value: "ORGANIZATION" },
];

export const DriveStageStatus = [
  { label: "Scheduled", value: "SCHEDULED" },
  { label: "Ongoing", value: "ONGOING" },
  { label: "Completed", value: "COMPLETED" },
  { label: "Rescheduled", value: "RESCHEDULED" },
];

export const SalaryType = [
  { label: "Monthly", value: "MONTHLY" },
  { label: "Annually", value: "ANNUALLY" },
];

export const DegreeChoices = [
  "10th Grade",
  "12th Grade",
  "High School Diploma",
  "Diploma",
  "Vocational Training",
  "Certificate Program",
  "Postgraduate Diploma",
  "Associate Degree",
  "Associate of Arts (AA)",
  "Associate of Science (AS)",
  "Associate of Applied Science (AAS)",
  "Bachelor's Degree",
  "Bachelor of Arts (BA)",
  "Bachelor of Science (BSc)",
  "Bachelor of Commerce (BCom)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Technology (B.Tech)",
  "Bachelor of Engineering (BE)",
  "Bachelor of Computer Applications (BCA)",
  "Bachelor of Science in Information Technology (BSc IT)",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Architecture (BArch)",
  "Bachelor of Design (BDes)",
  "Bachelor of Education (BEd)",
  "Bachelor of Pharmacy (BPharm)",
  "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
  "Bachelor of Laws (LLB)",
  "Master's Degree",
  "Master of Arts (MA)",
  "Master of Science (MSc)",
  "Master of Commerce (MCom)",
  "Master of Business Administration (MBA)",
  "Master of Technology (M.Tech)",
  "Master of Engineering (ME)",
  "Master of Computer Applications (MCA)",
  "Master of Science in Information Technology (MSc IT)",
  "Master of Fine Arts (MFA)",
  "Master of Architecture (MArch)",
  "Master of Design (MDes)",
  "Master of Education (MEd)",
  "Master of Pharmacy (MPharm)",
  "Master of Laws (LLM)",
  "Master of Philosophy (MPhil)",
  "Doctorate (PhD)",
  "Doctor of Medicine (MD)",
  "Doctor of Business Administration (DBA)",
  "Doctor of Education (EdD)",
  "Doctor of Engineering (EngD)",
  "Juris Doctor (JD)",
];

export const FieldOfStudyChoices = [
  "Computer Science",
  "Information Technology",
  "Software Engineering",
  "Data Science",
  "Cybersecurity",
  "Artificial Intelligence",
  "Business Administration",
  "Marketing",
  "Finance",
  "Accounting",
  "Economics",
  "Human Resources",
  "Entrepreneurship",
  "Medicine",
  "Nursing",
  "Pharmacy",
  "Dentistry",
  "Biotechnology",
  "Biomedical Engineering",
  "Law",
  "Political Science",
  "International Relations",
  "Psychology",
  "Sociology",
  "Philosophy",
  "Education",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Aerospace Engineering",
  "Chemical Engineering",
  "Environmental Science",
  "Physics",
  "Mathematics",
  "Statistics",
  "Astronomy",
  "Architecture",
  "Urban Planning",
  "Journalism",
  "Communication",
  "Graphic Design",
  "Fine Arts",
  "Music",
  "Theatre and Performing Arts",
  "History",
  "Anthropology",
  "Linguistics",
  "Agriculture",
  "Veterinary Science",
  "Hospitality and Tourism",
  "Sports Science",
  "Public Health",
  "Social Work",
  "Geology",
  "Marine Biology",
  "Zoology",
  "Religious Studies",
  "Library Science",
  "Fashion Design",
  "Culinary Arts",
  "Ethnic and Gender Studies",
];

export const ScoreTypeChoices = [
  { value: "CGPA", label: "CGPA" },
  { value: "SGPA", label: "SGPA" },
  { value: "PERCENTAGE", label: "Percentage" },
];

export const EducationModeChoices = [
  { value: "FULLTIME", label: "Fulltime" },
  { value: "DISTANCE", label: "Distance" },
  { value: "HYBRID", label: "Hybrid" },
  { value: "ONLINE", label: "Online" },
];

export const countriesAndCurrencies: any = [
  {
    label: "Afghanistan",
    currency_code: "AFN",
    currency_name: "Afghan Afghani (AFN)",
    value: "AF",
  },
  {
    label: "Albania",
    currency_code: "ALL",
    currency_name: "Albanian Lek (ALL)",
    value: "AL",
  },
  {
    label: "Algeria",
    currency_code: "DZD",
    currency_name: "Algerian Dinar (DZD)",
    value: "DZ",
  },
  {
    label: "Andorra",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "AD",
  },
  {
    label: "Angola",
    currency_code: "AOA",
    currency_name: "Angolan Kwanza (AOA)",
    value: "AO",
  },
  {
    label: "Antarctica",
    currency_code: null,
    currency_name: null,
    value: "AQ",
  },
  {
    label: "Argentina",
    currency_code: "ARS",
    currency_name: "Argentine Peso (ARS)",
    value: "AR",
  },
  {
    label: "Armenia",
    currency_code: "AMD",
    currency_name: "Armenian Dram (AMD)",
    value: "AM",
  },
  {
    label: "Aruba",
    currency_code: "AWG",
    currency_name: "Aruban Florin (AWG)",
    value: "AW",
  },
  {
    label: "Australia",
    currency_code: "AUD",
    currency_name: "Australian Dollar (AUD)",
    value: "AU",
  },
  {
    label: "Austria",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "AT",
  },
  {
    label: "Azerbaijan",
    currency_code: "AZN",
    currency_name: "Azerbaijani Manat (AZN)",
    value: "AZ",
  },
  {
    label: "Bahamas",
    currency_code: "BSD",
    currency_name: "Bahamian Dollar (BSD)",
    value: "BS",
  },
  {
    label: "Bahrain",
    currency_code: "BHD",
    currency_name: "Bahraini Dinar (BHD)",
    value: "BH",
  },
  {
    label: "Bangladesh",
    currency_code: "BDT",
    currency_name: "Bangladeshi Taka (BDT)",
    value: "BD",
  },
  {
    label: "Barbados",
    currency_code: "BBD",
    currency_name: "Barbadian Dollar (BBD)",
    value: "BB",
  },
  {
    label: "Belarus",
    currency_code: "BYN",
    currency_name: "Belarusian Ruble (BYN)",
    value: "BY",
  },
  {
    label: "Belgium",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "BE",
  },
  {
    label: "Belize",
    currency_code: "BZD",
    currency_name: "Belize Dollar (BZD)",
    value: "BZ",
  },
  {
    label: "Benin",
    currency_code: "XOF",
    currency_name: "West African CFA franc (XOF)",
    value: "BJ",
  },
  {
    label: "Bermuda",
    currency_code: "BMD",
    currency_name: "Bermudian Dollar (BMD)",
    value: "BM",
  },
  {
    label: "Bhutan",
    currency_code: "BTN",
    currency_name: "Bhutanese Ngultrum (BTN)",
    value: "BT",
  },
  {
    label: "Bolivia",
    currency_code: "BOB",
    currency_name: "Bolivian Boliviano (BOB)",
    value: "BO",
  },
  {
    label: "Bonaire, Sint Eustatius and Saba",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "BQ",
  },
  {
    label: "Bosnia and Herzegovina",
    currency_code: "BAM",
    currency_name: "Bosnia-Herzegovina Convertible Mark (BAM)",
    value: "BA",
  },
  {
    label: "Botswana",
    currency_code: "BWP",
    currency_name: "Botswanan Pula (BWP)",
    value: "BW",
  },
  {
    label: "Brazil",
    currency_code: "BRL",
    currency_name: "Brazilian Real (BRL)",
    value: "BR",
  },
  {
    label: "British Indian Ocean Territory",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "IO",
  },
  {
    label: "Brunei Darussalam",
    currency_code: "BND",
    currency_name: "Brunei Dollar (BND)",
    value: "BN",
  },
  {
    label: "Bulgaria",
    currency_code: "BGN",
    currency_name: "Bulgarian Lev (BGN)",
    value: "BG",
  },
  {
    label: "Burkina Faso",
    currency_code: "XOF",
    currency_name: "West African CFA franc (XOF)",
    value: "BF",
  },
  {
    label: "Burundi",
    currency_code: "BIF",
    currency_name: "Burundian Franc (BIF)",
    value: "BI",
  },
  {
    label: "Cambodia",
    currency_code: "KHR",
    currency_name: "Cambodian Riel (KHR)",
    value: "KH",
  },
  {
    label: "Cameroon",
    currency_code: "XAF",
    currency_name: "Central African CFA franc (XAF)",
    value: "CM",
  },
  {
    label: "Canada",
    currency_code: "CAD",
    currency_name: "Canadian Dollar (CAD)",
    value: "CA",
  },
  {
    label: "Cape Verde",
    currency_code: "CVE",
    currency_name: "Cape Verdean Escudo (CVE)",
    value: "CV",
  },
  {
    label: "Cayman Islands",
    currency_code: "KYD",
    currency_name: "Cayman Islands Dollar (KYD)",
    value: "KY",
  },
  {
    label: "Central African Republic",
    currency_code: "XAF",
    currency_name: "Central African CFA franc (XAF)",
    value: "CF",
  },
  {
    label: "Chad",
    currency_code: "XAF",
    currency_name: "Central African CFA franc (XAF)",
    value: "TD",
  },
  {
    label: "Chile",
    currency_code: "CLP",
    currency_name: "Chilean Peso (CLP)",
    value: "CL",
  },
  {
    label: "China",
    currency_code: "CNY",
    currency_name: "Chinese Yuan (CNY)",
    value: "CN",
  },
  {
    label: "Christmas Island",
    currency_code: null,
    currency_name: null,
    value: "CX",
  },
  {
    label: "Cocos (Keeling) Islands",
    currency_code: null,
    currency_name: null,
    value: "CC",
  },
  {
    label: "Colombia",
    currency_code: "COP",
    currency_name: "Colombian Peso (COP)",
    value: "CO",
  },
  {
    label: "Comoros",
    currency_code: "KMF",
    currency_name: "Comorian Franc (KMF)",
    value: "KM",
  },
  {
    label: "Congo",
    currency_code: "CDF",
    currency_name: "Congolese Franc (CDF)",
    value: "CG",
  },
  {
    label: "Congo, Democratic Republic of the",
    currency_code: "CDF",
    currency_name: "Congolese Franc (CDF)",
    value: "CD",
  },
  {
    label: "Cook Islands",
    currency_code: "NZD",
    currency_name: "New Zealand Dollar (NZD)",
    value: "CK",
  },
  {
    label: "Costa Rica",
    currency_code: "CRC",
    currency_name: "Costa Rican Colón (CRC)",
    value: "CR",
  },
  {
    label: "Côte d'Ivoire",
    currency_code: "XOF",
    currency_name: "West African CFA franc (XOF)",
    value: "CI",
  },
  {
    label: "Croatia",
    currency_code: "HRK",
    currency_name: "Croatian Kuna (HRK)",
    value: "HR",
  },
  {
    label: "Cuba",
    currency_code: "CUP",
    currency_name: "Cuban Peso (CUP)",
    value: "CU",
  },
  {
    label: "Curaçao",
    currency_code: "ANG",
    currency_name: "Netherlands Antillean Guilder (ANG)",
    value: "CW",
  },
  {
    label: "Cyprus",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "CY",
  },
  {
    label: "Czech Republic",
    currency_code: "CZK",
    currency_name: "Czech Republic Koruna (CZK)",
    value: "CZ",
  },
  {
    label: "Denmark",
    currency_code: "DKK",
    currency_name: "Danish Krone (DKK)",
    value: "DK",
  },
  {
    label: "Djibouti",
    currency_code: "DJF",
    currency_name: "Djiboutian Franc (DJF)",
    value: "DJ",
  },
  {
    label: "Dominica",
    currency_code: "XCD",
    currency_name: "East Caribbean Dollar (XCD)",
    value: "DM",
  },
  {
    label: "Dominican Republic",
    currency_code: "DOP",
    currency_name: "Dominican Peso (DOP)",
    value: "DO",
  },
  {
    label: "Ecuador",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "EC",
  },
  {
    label: "Egypt",
    currency_code: "EGP",
    currency_name: "Egyptian Pound (EGP)",
    value: "EG",
  },
  {
    label: "El Salvador",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "SV",
  },
  {
    label: "Equatorial Guinea",
    currency_code: "XAF",
    currency_name: "Central African CFA franc (XAF)",
    value: "GQ",
  },
  {
    label: "Eritrea",
    currency_code: "ERN",
    currency_name: "Eritrean Nakfa (ERN)",
    value: "ER",
  },
  {
    label: "Estonia",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "EE",
  },
  {
    label: "Ethiopia",
    currency_code: "ETB",
    currency_name: "Ethiopian Birr (ETB)",
    value: "ET",
  },
  {
    label: "Falkland Islands (Malvinas)",
    currency_code: "FKP",
    currency_name: "Falkland Islands Pound (FKP)",
    value: "FK",
  },
  {
    label: "Faroe Islands",
    currency_code: "DKK",
    currency_name: "Danish Krone (DKK)",
    value: "FO",
  },
  {
    label: "Fiji",
    currency_code: "FJD",
    currency_name: "Fijian Dollar (FJD)",
    value: "FJ",
  },
  {
    label: "Finland",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "FI",
  },
  {
    label: "France",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "FR",
  },
  {
    label: "French Guiana",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "GF",
  },
  {
    label: "French Polynesia",
    currency_code: "XPF",
    currency_name: "CFP Franc (XPF)",
    value: "PF",
  },
  {
    label: "French Southern Territories",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "TF",
  },
  {
    label: "Gabon",
    currency_code: "XAF",
    currency_name: "Central African CFA franc (XAF)",
    value: "GA",
  },
  {
    label: "Gambia",
    currency_code: "GMD",
    currency_name: "Gambian Dalasi (GMD)",
    value: "GM",
  },
  {
    label: "Georgia",
    currency_code: "GEL",
    currency_name: "Georgian Lari (GEL)",
    value: "GE",
  },
  {
    label: "Germany",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "DE",
  },
  {
    label: "Ghana",
    currency_code: "GHS",
    currency_name: "Ghanaian Cedi (GHS)",
    value: "GH",
  },
  {
    label: "Gibraltar",
    currency_code: "GIP",
    currency_name: "Gibraltar Pound (GIP)",
    value: "GI",
  },
  {
    label: "Greece",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "GR",
  },
  {
    label: "Greenland",
    currency_code: "DKK",
    currency_name: "Danish Krone (DKK)",
    value: "GL",
  },
  {
    label: "Grenada",
    currency_code: "XCD",
    currency_name: "East Caribbean Dollar (XCD)",
    value: "GD",
  },
  {
    label: "Guadeloupe",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "GP",
  },
  {
    label: "Guam",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "GU",
  },
  {
    label: "Guatemala",
    currency_code: "GTQ",
    currency_name: "Guatemalan Quetzal (GTQ)",
    value: "GT",
  },
  {
    label: "Guernsey",
    currency_code: "GBP",
    currency_name: "British Pound Sterling (GBP)",
    value: "GG",
  },
  {
    label: "Guinea",
    currency_code: "GNF",
    currency_name: "Guinean Franc (GNF)",
    value: "GN",
  },
  {
    label: "Guinea-Bissau",
    currency_code: "XOF",
    currency_name: "West African CFA franc (XOF)",
    value: "GW",
  },
  {
    label: "Guyana",
    currency_code: "GYD",
    currency_name: "Guyanaese Dollar (GYD)",
    value: "GY",
  },
  {
    label: "Haiti",
    currency_code: "HTG",
    currency_name: "Haitian Gourde (HTG)",
    value: "HT",
  },
  {
    label: "Heard Island and McDonald Islands",
    currency_code: null,
    currency_name: null,
    value: "HM",
  },
  {
    label: "Holy See (Vatican City State)",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "VA",
  },
  {
    label: "Honduras",
    currency_code: "HNL",
    currency_name: "Honduran Lempira (HNL)",
    value: "HN",
  },
  {
    label: "Hong Kong",
    currency_code: "HKD",
    currency_name: "Hong Kong Dollar (HKD)",
    value: "HK",
  },
  {
    label: "Hungary",
    currency_code: "HUF",
    currency_name: "Hungarian Forint (HUF)",
    value: "HU",
  },
  {
    label: "Iceland",
    currency_code: "ISK",
    currency_name: "Icelandic Króna (ISK)",
    value: "IS",
  },
  {
    label: "India",
    currency_code: "INR",
    currency_name: "Indian Rupee (INR)",
    value: "IN",
  },
  {
    label: "Indonesia",
    currency_code: "IDR",
    currency_name: "Indonesian Rupiah (IDR)",
    value: "ID",
  },
  {
    label: "Iran, Islamic Republic of",
    currency_code: "IRR",
    currency_name: "Iranian Rial (IRR)",
    value: "IR",
  },
  {
    label: "Iraq",
    currency_code: "IQD",
    currency_name: "Iraqi Dinar (IQD)",
    value: "IQ",
  },
  {
    label: "Ireland",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "IE",
  },
  {
    label: "Isle of Man",
    currency_code: "GBP",
    currency_name: "British Pound Sterling (GBP)",
    value: "IM",
  },
  {
    label: "Israel",
    currency_code: "ILS",
    currency_name: "Israeli New Sheqel (ILS)",
    value: "IL",
  },
  {
    label: "Italy",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "IT",
  },
  {
    label: "Jamaica",
    currency_code: "JMD",
    currency_name: "Jamaican Dollar (JMD)",
    value: "JM",
  },
  {
    label: "Japan",
    currency_code: "JPY",
    currency_name: "Japanese Yen (JPY)",
    value: "JP",
  },
  {
    label: "Jersey",
    currency_code: "GBP",
    currency_name: "British Pound Sterling (GBP)",
    value: "JE",
  },
  {
    label: "Jordan",
    currency_code: "JOD",
    currency_name: "Jordanian Dinar (JOD)",
    value: "JO",
  },
  {
    label: "Kazakhstan",
    currency_code: "KZT",
    currency_name: "Kazakhstani Tenge (KZT)",
    value: "KZ",
  },
  {
    label: "Kenya",
    currency_code: "KES",
    currency_name: "Kenyan Shilling (KES)",
    value: "KE",
  },
  {
    label: "Kiribati",
    currency_code: "AUD",
    currency_name: "Australian Dollar (AUD)",
    value: "KI",
  },
  {
    label: "Korea, Democratic People's Republic of",
    currency_code: "KPW",
    currency_name: "North Korean Won (KPW)",
    value: "KP",
  },
  {
    label: "Korea, Republic of",
    currency_code: "KRW",
    currency_name: "South Korean Won (KRW)",
    value: "KR",
  },
  {
    label: "Kosovo",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "XK",
  },
  {
    label: "Kuwait",
    currency_code: "KWD",
    currency_name: "Kuwaiti Dinar (KWD)",
    value: "KW",
  },
  {
    label: "Kyrgyzstan",
    currency_code: "KGS",
    currency_name: "Kyrgystani Som (KGS)",
    value: "KG",
  },
  {
    label: "Lao People's Democratic Republic",
    currency_code: "LAK",
    currency_name: "Laotian Kip (LAK)",
    value: "LA",
  },
  {
    label: "Latvia",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "LV",
  },
  {
    label: "Lebanon",
    currency_code: "LBP",
    currency_name: "Lebanese Pound (LBP)",
    value: "LB",
  },
  {
    label: "Lesotho",
    currency_code: "LSL",
    currency_name: "Lesotho Loti (LSL)",
    value: "LS",
  },
  {
    label: "Liberia",
    currency_code: "LRD",
    currency_name: "Liberian Dollar (LRD)",
    value: "LR",
  },
  {
    label: "Libya",
    currency_code: "LYD",
    currency_name: "Libyan Dinar (LYD)",
    value: "LY",
  },
  {
    label: "Liechtenstein",
    currency_code: "CHF",
    currency_name: "Swiss Franc (CHF)",
    value: "LI",
  },
  {
    label: "Lithuania",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "LT",
  },
  {
    label: "Luxembourg",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "LU",
  },
  {
    label: "Macao",
    currency_code: "MOP",
    currency_name: "Macanese Pataca (MOP)",
    value: "MO",
  },
  {
    label: "Macedonia, the Former Yugoslav Republic of",
    currency_code: "MKD",
    currency_name: "Macedonian Denar (MKD)",
    value: "MK",
  },
  {
    label: "Madagascar",
    currency_code: "MGA",
    currency_name: "Malagasy Ariary (MGA)",
    value: "MG",
  },
  {
    label: "Malawi",
    currency_code: "MWK",
    currency_name: "Malawian Kwacha (MWK)",
    value: "MW",
  },
  {
    label: "Malaysia",
    currency_code: "MYR",
    currency_name: "Malaysian Ringgit (MYR)",
    value: "MY",
  },
  {
    label: "Maldives",
    currency_code: "MVR",
    currency_name: "Maldivian Rufiyaa (MVR)",
    value: "MV",
  },
  {
    label: "Mali",
    currency_code: "XOF",
    currency_name: "West African CFA franc (XOF)",
    value: "ML",
  },
  {
    label: "Malta",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "MT",
  },
  {
    label: "Marshall Islands",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "MH",
  },
  {
    label: "Martinique",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "MQ",
  },
  {
    label: "Mauritania",
    currency_code: "MRU",
    currency_name: "Mauritanian Ouguiya (MRU)",
    value: "MR",
  },
  {
    label: "Mauritius",
    currency_code: "MUR",
    currency_name: "Mauritian Rupee (MUR)",
    value: "MU",
  },
  {
    label: "Mayotte",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "YT",
  },
  {
    label: "Mexico",
    currency_code: "MXN",
    currency_name: "Mexican Peso (MXN)",
    value: "MX",
  },
  {
    label: "Micronesia, Federated States of",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "FM",
  },
  {
    label: "Moldova, Republic of",
    currency_code: "MDL",
    currency_name: "Moldovan Leu (MDL)",
    value: "MD",
  },
  {
    label: "Monaco",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "MC",
  },
  {
    label: "Mongolia",
    currency_code: "MNT",
    currency_name: "Mongolian Tugrik (MNT)",
    value: "MN",
  },
  {
    label: "Montenegro",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "ME",
  },
  {
    label: "Montserrat",
    currency_code: "XCD",
    currency_name: "East Caribbean Dollar (XCD)",
    value: "MS",
  },
  {
    label: "Morocco",
    currency_code: "MAD",
    currency_name: "Moroccan Dirham (MAD)",
    value: "MA",
  },
  {
    label: "Mozambique",
    currency_code: "MZN",
    currency_name: "Mozambican Metical (MZN)",
    value: "MZ",
  },
  {
    label: "Myanmar",
    currency_code: "MMK",
    currency_name: "Myanmar Kyat (MMK)",
    value: "MM",
  },
  {
    label: "Namibia",
    currency_code: "NAD",
    currency_name: "Namibian Dollar (NAD)",
    value: "NA",
  },
  {
    label: "Nauru",
    currency_code: "AUD",
    currency_name: "Australian Dollar (AUD)",
    value: "NR",
  },
  {
    label: "Nepal",
    currency_code: "NPR",
    currency_name: "Nepalese Rupee (NPR)",
    value: "NP",
  },
  {
    label: "Netherlands",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "NL",
  },
  {
    label: "New Caledonia",
    currency_code: "XPF",
    currency_name: "CFP Franc (XPF)",
    value: "NC",
  },
  {
    label: "New Zealand",
    currency_code: "NZD",
    currency_name: "New Zealand Dollar (NZD)",
    value: "NZ",
  },
  {
    label: "Nicaragua",
    currency_code: "NIO",
    currency_name: "Nicaraguan Córdoba (NIO)",
    value: "NI",
  },
  {
    label: "Niger",
    currency_code: "XOF",
    currency_name: "West African CFA franc (XOF)",
    value: "NE",
  },
  {
    label: "Nigeria",
    currency_code: "NGN",
    currency_name: "Nigerian Naira (NGN)",
    value: "NG",
  },
  {
    label: "Niue",
    currency_code: "NZD",
    currency_name: "New Zealand Dollar (NZD)",
    value: "NU",
  },
  {
    label: "Norfolk Island",
    currency_code: "AUD",
    currency_name: "Australian Dollar (AUD)",
    value: "NF",
  },
  {
    label: "Northern Mariana Islands",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "MP",
  },
  {
    label: "Norway",
    currency_code: "NOK",
    currency_name: "Norwegian Krone (NOK)",
    value: "NO",
  },
  {
    label: "Oman",
    currency_code: "OMR",
    currency_name: "Omani Rial (OMR)",
    value: "OM",
  },
  {
    label: "Pakistan",
    currency_code: "PKR",
    currency_name: "Pakistani Rupee (PKR)",
    value: "PK",
  },
  {
    label: "Palau",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "PW",
  },
  {
    label: "Palestine, State of",
    currency_code: "ILS",
    currency_name: "Israeli New Sheqel (ILS)",
    value: "PS",
  },
  {
    label: "Panama",
    currency_code: "PAB",
    currency_name: "Panamanian Balboa (PAB)",
    value: "PA",
  },
  {
    label: "Papua New Guinea",
    currency_code: "PGK",
    currency_name: "Papua New Guinean Kina (PGK)",
    value: "PG",
  },
  {
    label: "Paraguay",
    currency_code: "PYG",
    currency_name: "Paraguayan Guarani (PYG)",
    value: "PY",
  },
  {
    label: "Peru",
    currency_code: "PEN",
    currency_name: "Peruvian Nuevo Sol (PEN)",
    value: "PE",
  },
  {
    label: "Philippines",
    currency_code: "PHP",
    currency_name: "Philippine Peso (PHP)",
    value: "PH",
  },
  {
    label: "Pitcairn",
    currency_code: null,
    currency_name: null,
    value: "PN",
  },
  {
    label: "Poland",
    currency_code: "PLN",
    currency_name: "Polish Zloty (PLN)",
    value: "PL",
  },
  {
    label: "Portugal",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "PT",
  },
  {
    label: "Puerto Rico",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "PR",
  },
  {
    label: "Qatar",
    currency_code: "QAR",
    currency_name: "Qatari Rial (QAR)",
    value: "QA",
  },
  {
    label: "Réunion",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "RE",
  },
  {
    label: "Romania",
    currency_code: "RON",
    currency_name: "Romanian Leu (RON)",
    value: "RO",
  },
  {
    label: "Russian Federation",
    currency_code: "RUB",
    currency_name: "Russian Ruble (RUB)",
    value: "RU",
  },
  {
    label: "Rwanda",
    currency_code: "RWF",
    currency_name: "Rwandan Franc (RWF)",
    value: "RW",
  },
  {
    label: "Saint Barthélemy",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "BL",
  },
  {
    label: "Saint Helena, Ascension and Tristan da Cunha",
    currency_code: "SHP",
    currency_name: "Saint Helena Pound (SHP)",
    value: "SH",
  },
  {
    label: "Saint Kitts and Nevis",
    currency_code: "XCD",
    currency_name: "East Caribbean Dollar (XCD)",
    value: "KN",
  },
  {
    label: "Saint Lucia",
    currency_code: "XCD",
    currency_name: "East Caribbean Dollar (XCD)",
    value: "LC",
  },
  {
    label: "Saint Martin (French part)",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "MF",
  },
  {
    label: "Saint Pierre and Miquelon",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "PM",
  },
  {
    label: "Saint Vincent and the Grenadines",
    currency_code: "XCD",
    currency_name: "East Caribbean Dollar (XCD)",
    value: "VC",
  },
  {
    label: "Samoa",
    currency_code: "WST",
    currency_name: "Samoan Tala (WST)",
    value: "WS",
  },
  {
    label: "San Marino",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "SM",
  },
  {
    label: "Sao Tome and Principe",
    currency_code: "STN",
    currency_name: "São Tomé and Príncipe Dobra (STN)",
    value: "ST",
  },
  {
    label: "Saudi Arabia",
    currency_code: "SAR",
    currency_name: "Saudi Riyal (SAR)",
    value: "SA",
  },
  {
    label: "Senegal",
    currency_code: "XOF",
    currency_name: "West African CFA franc (XOF)",
    value: "SN",
  },
  {
    label: "Serbia",
    currency_code: "RSD",
    currency_name: "Serbian Dinar (RSD)",
    value: "RS",
  },
  {
    label: "Seychelles",
    currency_code: "SCR",
    currency_name: "Seychellois Rupee (SCR)",
    value: "SC",
  },
  {
    label: "Sierra Leone",
    currency_code: "SLL",
    currency_name: "Sierra Leonean Leone (SLL)",
    value: "SL",
  },
  {
    label: "Singapore",
    currency_code: "SGD",
    currency_name: "Singapore Dollar (SGD)",
    value: "SG",
  },
  {
    label: "Sint Maarten (Dutch part)",
    currency_code: "ANG",
    currency_name: "Netherlands Antillean Guilder (ANG)",
    value: "SX",
  },
  {
    label: "Slovakia",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "SK",
  },
  {
    label: "Slovenia",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "SI",
  },
  {
    label: "Solomon Islands",
    currency_code: "SBD",
    currency_name: "Solomon Islands Dollar (SBD)",
    value: "SB",
  },
  {
    label: "Somalia",
    currency_code: "SOS",
    currency_name: "Somali Shilling (SOS)",
    value: "SO",
  },
  {
    label: "South Africa",
    currency_code: "ZAR",
    currency_name: "South African Rand (ZAR)",
    value: "ZA",
  },
  {
    label: "South Georgia and the South Sandwich Islands",
    currency_code: "GBP",
    currency_name: "British Pound Sterling (GBP)",
    value: "GS",
  },
  {
    label: "South Sudan",
    currency_code: "SSP",
    currency_name: "South Sudanese Pound (SSP)",
    value: "SS",
  },
  {
    label: "Spain",
    currency_code: "EUR",
    currency_name: "Euro (EUR)",
    value: "ES",
  },
  {
    label: "Sri Lanka",
    currency_code: "LKR",
    currency_name: "Sri Lankan Rupee (LKR)",
    value: "LK",
  },
  {
    label: "Sudan",
    currency_code: "SDG",
    currency_name: "Sudanese Pound (SDG)",
    value: "SD",
  },
  {
    label: "Suriname",
    currency_code: "SRD",
    currency_name: "Surinamese Dollar (SRD)",
    value: "SR",
  },
  {
    label: "Svalbard and Jan Mayen",
    currency_code: "NOK",
    currency_name: "Norwegian Krone (NOK)",
    value: "SJ",
  },
  {
    label: "Swaziland",
    currency_code: "SZL",
    currency_name: "Swazi Lilangeni (SZL)",
    value: "SZ",
  },
  {
    label: "Sweden",
    currency_code: "SEK",
    currency_name: "Swedish Krona (SEK)",
    value: "SE",
  },
  {
    label: "Switzerland",
    currency_code: "CHF",
    currency_name: "Swiss Franc (CHF)",
    value: "CH",
  },
  {
    label: "Syrian Arab Republic",
    currency_code: "SYP",
    currency_name: "Syrian Pound (SYP)",
    value: "SY",
  },
  {
    label: "Taiwan, Province of China",
    currency_code: "TWD",
    currency_name: "New Taiwan Dollar (TWD)",
    value: "TW",
  },
  {
    label: "Tajikistan",
    currency_code: "TJS",
    currency_name: "Tajikistani Somoni (TJS)",
    value: "TJ",
  },
  {
    label: "Tanzania, United Republic of",
    currency_code: "TZS",
    currency_name: "Tanzanian Shilling (TZS)",
    value: "TZ",
  },
  {
    label: "Thailand",
    currency_code: "THB",
    currency_name: "Thai Baht (THB)",
    value: "TH",
  },
  {
    label: "Timor-Leste",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "TL",
  },
  {
    label: "Togo",
    currency_code: "XOF",
    currency_name: "West African CFA franc (XOF)",
    value: "TG",
  },
  {
    label: "Tokelau",
    currency_code: "NZD",
    currency_name: "New Zealand Dollar (NZD)",
    value: "TK",
  },
  {
    label: "Tonga",
    currency_code: "TOP",
    currency_name: "Tongan Pa'anga (TOP)",
    value: "TO",
  },
  {
    label: "Trinidad and Tobago",
    currency_code: "TTD",
    currency_name: "Trinidad and Tobago Dollar (TTD)",
    value: "TT",
  },
  {
    label: "Tunisia",
    currency_code: "TND",
    currency_name: "Tunisian Dinar (TND)",
    value: "TN",
  },
  {
    label: "Turkey",
    currency_code: "TRY",
    currency_name: "Turkish Lira (TRY)",
    value: "TR",
  },
  {
    label: "Turkmenistan",
    currency_code: "TMT",
    currency_name: "Turkmenistani Manat (TMT)",
    value: "TM",
  },
  {
    label: "Turks and Caicos Islands",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "TC",
  },
  {
    label: "Tuvalu",
    currency_code: "AUD",
    currency_name: "Australian Dollar (AUD)",
    value: "TV",
  },
  {
    label: "Uganda",
    currency_code: "UGX",
    currency_name: "Ugandan Shilling (UGX)",
    value: "UG",
  },
  {
    label: "Ukraine",
    currency_code: "UAH",
    currency_name: "Ukrainian Hryvnia (UAH)",
    value: "UA",
  },
  {
    label: "United Arab Emirates",
    currency_code: "AED",
    currency_name: "United Arab Emirates Dirham (AED)",
    value: "AE",
  },
  {
    label: "United Kingdom",
    currency_code: "GBP",
    currency_name: "British Pound Sterling (GBP)",
    value: "GB",
  },
  {
    label: "United States",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "US",
  },
  {
    label: "United States Minor Outlying Islands",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "UM",
  },
  {
    label: "Uruguay",
    currency_code: "UYU",
    currency_name: "Uruguayan Peso (UYU)",
    value: "UY",
  },
  {
    label: "Uzbekistan",
    currency_code: "UZS",
    currency_name: "Uzbekistan Som (UZS)",
    value: "UZ",
  },
  {
    label: "Vanuatu",
    currency_code: "VUV",
    currency_name: "Vanuatu Vatu (VUV)",
    value: "VU",
  },
  {
    label: "Venezuela, Bolivarian Republic of",
    currency_code: "VES",
    currency_name: "Venezuelan Bolívar (VES)",
    value: "VE",
  },
  {
    label: "Viet Nam",
    currency_code: "VND",
    currency_name: "Vietnamese Dong (VND)",
    value: "VN",
  },
  {
    label: "Virgin Islands, British",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "VG",
  },
  {
    label: "Virgin Islands, U.S.",
    currency_code: "USD",
    currency_name: "United States Dollar (USD)",
    value: "VI",
  },
  {
    label: "Wallis and Futuna",
    currency_code: "XPF",
    currency_name: "CFP Franc (XPF)",
    value: "WF",
  },
  {
    label: "Western Sahara",
    currency_code: "MAD",
    currency_name: "Moroccan Dirham (MAD)",
    value: "EH",
  },
  {
    label: "Yemen",
    currency_code: "YER",
    currency_name: "Yemeni Rial (YER)",
    value: "YE",
  },
  {
    label: "Zambia",
    currency_code: "ZMW",
    currency_name: "Zambian Kwacha (ZMW)",
    value: "ZM",
  },
  {
    label: "Zimbabwe",
    currency_code: "ZWL",
    currency_name: "Zimbabwean Dollar (ZWL)",
    value: "ZW",
  },
];

export const jobDesignations = [
  // Software & IT
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "Cybersecurity Analyst",
  "QA Engineer",
  "UI/UX Designer",
  "Cloud Engineer",
  "Database Administrator",
  "Product Manager",

  // Management & Business
  "Business Development Executive (BDE)",
  "Business Development Manager (BDM)",
  "Sales Executive",
  "Marketing Manager",
  "HR Manager",
  "Operations Manager",
  "Project Manager",
  "Chief Executive Officer (CEO)",
  "Chief Operating Officer (COO)",
  "Chief Technology Officer (CTO)",

  // Finance & Accounting
  "Accountant",
  "Financial Analyst",
  "Investment Banker",
  "Auditor",
  "Tax Consultant",
  "Chief Financial Officer (CFO)",

  // Healthcare & Medical
  "Doctor",
  "Nurse",
  "Surgeon",
  "Pharmacist",
  "Medical Researcher",
  "Lab Technician",

  // Education & Research
  "Professor",
  "Lecturer",
  "Research Scientist",
  "Academic Coordinator",
  "Principal",

  // Customer Support & Service
  "Customer Support Executive",
  "Customer Service Manager",
  "Technical Support Engineer",
];

export const testimonialCandidates = [
  {
    image: Testimonial3,
    name: "Navpreet Kaur",
    feedback:
      "My journey to becoming a professional was greatly supported by SkillBrew.ai. The daily contests and carefully curated questions, along with the IDE and code collaboration features, made DSA practice engaging and effective. SkillBrew helped me navigate the learning phase, practice consistently, and ultimately secure my job. I highly recommend it for anyone serious about advancing their tech career.",
    designation: "Associate Developer",
    companyName: "Mandelbulb Technologies",
  },
  {
    image: Testimonial1,
    name: "Faisal Nazir",
    feedback:
      "In my final year of college, I stumbled upon SkillBrew.ai while searching for a solid platform to practice DSA. It turned out to be a game-changer.The coding IDE and the practice questions were exactly what I needed to sharpen my skills and land a job.",
    designation: "Software Development Engineer",
    companyName: "American Chase",
  },
  {
    image: Testimonial2,
    name: "Janvi Sharma",
    feedback:
      "As a tech enthusiast, I struggled with Data Structures and Algorithms (DSA) until I found SkillBrew. The platform's valuable features like code collaboration. Practising with friends made the experience enjoyable and effective. With SkillBrew's support, I improved my skills and secured a job. Thanks to SkillBrew for helping me bridge the gap between learning and landing a job!",
    designation: "Software  Engineer Learning -1",
    companyName: "Consultadd Services Private Limited",
  },
  {
    image: Testimonial6,
    name: "Shubhanshu Mishra",
    feedback:
      "While struggling for a job, I was confident in my knowledge of different tech stacks and felt prepared for interviews, but I had difficulty with the coding rounds. I turned to SkillBrew for help and started practicing with the available questions. I involved my friends using the code collaboration feature, creating a competitive environment with quizzes and weekly contests. Slowly, I gained confidence and ultimately sealed the opportunity.",
    designation: "Python Developer",
    companyName: "Ollosoft Technologies Private Limited",
  },
  {
    image: Testimonial5,
    name: "Vikas Kumar Jain",
    feedback:
      "During my preparation phase for job interviews, Skilbrew proved to be a transformative tool. Its features maintained my enthusiasm, and the daily coding challenges substantially enhanced my Data Structures and Algorithms proficiency",
    designation: "Android Developer",
    companyName: "Ahead Websoft Technologies",
  },
  {
    image: Testimonial4,
    name: "Prashant Lalwani",
    feedback:
      "I started my coding journey with the SkillBrew IDE, beginning with their practice questions that were tagged by different topics. When I gained confidence, I began participating in the contests, and the daily quizzes helped me get a strong command over DSA topics. This preparation really helped during my interview, and I was able to crack the job.",
    designation: "Software Engineer- Trainee",
    companyName: "Biz4 Group LLC",
  },
];

export const companyLogos = [
  {
    src: Companies1,
    alt: "Company Logo 1",
  },
  {
    src: Companies2,
    alt: "Company Logo 2",
  },
  {
    src: Companies3,
    alt: "Company Logo 3",
  },
  {
    src: Companies4,
    alt: "Company Logo 4",
  },
  {
    src: Companies5,
    alt: "Company Logo 5",
  },
  {
    src: Companies6,
    alt: "Company Logo 6",
  },
];

export const officeLocationData = [
  {
    icon: "fa-solid fa-envelope",
    title: "India",
    email: "info@skillbrew.com",
    phone: "+91-90766 24183",
    location: "https://www.google.com/maps?q=Brudite ",
    imageUrl: OfficeIndia,
    iconColor: "#FFAA00",
  },
  {
    icon: "fa-solid fa-envelope",
    title: "USA",
    email: "info@skillbrew.com",
    phone: "+1 (551) 998-2691",
    location:
      "https://www.google.com/maps/search/?api=1&query=2090+Dunwoody+Club+Dr%2C+Ste+106+%235132%2C+Atlanta%2C+GA%2C+30350%2C+USA",
    imageUrl: OfficeUs,
    iconColor: "#33907C",
  },
];

export const teamMembers = [
  {
    id: 1,
    name: "Ritu Soni",
    position: "CTO & Co-Founder",
    imageSrc: Ritu,
    linkedinprofile: "https://www.linkedin.com/in/ritu-soni1",
  },
  {
    id: 2,
    name: "Rishabh Tiwari",
    position: "CEO & Co-Founder",
    imageSrc: Rishabh,
    linkedinprofile: "https://www.linkedin.com/in/devcoder/",
  },
  {
    id: 3,
    name: "Nirvika Sharma",
    position: "Lead-Talent & People Operations",
    imageSrc: Nirvika,
    linkedinprofile: "https://www.linkedin.com/in/nirvika-sharma-08a755294",
  },
  {
    id: 4,
    name: "Ajeet Singh",
    position: "Lead Software Engineer",
    imageSrc: Ajeet,
    linkedinprofile: "https://www.linkedin.com/in/ajeet-singh-6372631a1",
  },
  {
    id: 5,
    name: "Vipul Jain",
    position: "Backend Developer",
    imageSrc: Vipul,
    linkedinprofile: "https://www.linkedin.com/in/vipul-jain-v8441j/",
  },

  {
    id: 6,
    name: "Rashid Ali",
    position: "Frontend Developer",
    imageSrc: Rashid,
    linkedinprofile: "https://www.linkedin.com/in/myselfrashid/",
  },

  {
    id: 7,
    name: "Dev Aaryan",
    position: "Backend Developer",
    imageSrc: Dev,
    linkedinprofile: "https://www.linkedin.com/in/dev-aaryan/",
  },
  {
    id: 8,
    name: "Sanyam Kumat",
    position: "Backend Developer",
    imageSrc: Sanyam,
    linkedinprofile: "https://www.linkedin.com/in/sanyamkumat/",
  },
  {
    id: 9,
    name: "Arpit Pareek",
    position: "UI/UX Designer",
    imageSrc: Arpit,
    linkedinprofile: "https://www.linkedin.com/in/mr-arpit-pareek/",
  },
  {
    id: 10,
    name: "Ayush Raj",
    position: "UI/UX Designer",
    imageSrc: Ayush,
    linkedinprofile: "https://www.linkedin.com/in/ayushux/",
  },
  {
    id: 11,
    name: "Yashasvi Chaturvedi",
    position: "Digital Media Associate",
    imageSrc: Yashasvi,
    linkedinprofile:
      "https://www.linkedin.com/in/yashasvi-chaturvedi-948771301/",
  },
  {
    id: 12,
    name: "Lakshyaveer Singh",
    position: "Digital Media Associate",
    imageSrc: Lakshyaveer,
    linkedinprofile:
      "https://www.linkedin.com/in/lakshyaveer-singh-khinchi-02ba54211/",
  },
];

export const valueCardsData = [
  {
    id: 0,
    icon: Hint,
    title: "Innovation",
    weAllAboutText:
      "We’re all about pushing boundaries at Skillbrew. By using AI, we make learning tech easier and more impactful for everyone.",
  },
  {
    id: 1,
    icon: Accountable,
    title: "Accountability",
    weAllAboutText:
      "We stand by everything we create. Our team ensures that every feature in Skillbrew is reliable and meets the high standards you expect.",
  },
  {
    id: 2,
    icon: Commitment,
    title: "Commitment",
    weAllAboutText:
      "We’re committed to your success. With our comprehensive training programs, we’re here to help you grow and thrive in your tech career.",
  },
  {
    id: 3,
    icon: Delivery,
    title: "Delivery",
    weAllAboutText:
      "We focus on delivering top-notch experiences, so you can trust Skillbrew to provide the skills and confidence you need to succeed.",
  },
];

export const testFilterOption = [
  { value: "", label: "All Assessments" },
  {
    value: "ONGOING",
    label: "Ongoing Assessments",
  },
  {
    value: "UPCOMING",
    label: "Upcoming Assessments",
  },
  {
    value: "COMPLETED",
    label: "Completed Assessments",
  },
  { value: "DRAFT", label: "Draft Assessments" },
];

export const driveFilterOption = [
  {
    value: "SCHEDULED",
    label: "Schedule Drive",
  },
  {
    value: "ONGOING",
    label: "Ongoing Drive",
  },
  {
    value: "COMPLETED",
    label: "Completed Drive",
  },
  { value: "DRAFT", label: "Draft Drive" },
];

export const userFilterOption = [
  { value: "name", label: "By Name" },
  { value: "email", label: "By Email" },
];

export const interviewFilterOption = [
  { value: "", label: "All" },
  { value: "ongoing", label: "Ongoing Interviews" },
  { value: "upcoming", label: "Upcoming Interviews" },
  { value: "completed", label: "Completed Interviews" },
  { value: "draft", label: "Draft Interviews" },
];

export const contactStatusOption = [
  {
    value: "CALLED",
    label: "Called",
    class: "success-status",
    icon: Icons?.called,
  },
  {
    value: "MESSAGED",
    label: "Messaged",
    class: "warning-status",
    icon: Icons?.messaged,
  },
  {
    value: "NOTPICKED",
    label: "Not Picked",
    class: "danger-status",
    icon: Icons?.notPicked,
  },
  {
    value: "NOTREACHABLE",
    label: "Not Reachable",
    class: "primary-status",
    icon: Icons?.notReachable,
  },
];

export const driveCollaboratorPermissions = [
  {
    name: "View Drive Profile",
    code_name: "view_driveprofile",
  },
  {
    name: "Update Drive Profile",
    code_name: "update_driveprofile",
  },
  {
    name: "Manage Drive Profile",
    code_name: "manage_driveprofile",
  },
  {
    name: "View Drive Collaborator",
    code_name: "view_drivecollaborator",
  },
  {
    name: "Manage Drive Collaborator",
    code_name: "manage_drivecollaborator",
  },
  {
    name: "Delete Drive Collaborator",
    code_name: "delete_drivecollaborator",
  },
];

export const driveMenuOption = [
  { value: "stages", label: "Stages" },
  { value: "phases", label: "Employment Phases" },
  { value: "applicants", label: "Applicants" },
  { value: "collaborations", label: "Collaborations" },
  { value: "job-details", label: "More Job Details" },
  { value: "discussion", label: "Discussion" },
];

export const ResumeCompatibilityDetailHeaders = [
  { value: "strengths", label: "Strenghts" },
  { value: "weaknesses_or_gaps", label: "Weaknesses & Gaps" },
  { value: "skills_and_competencies", label: "Skills & Competencies" },
  { value: "achievements_and_impact", label: "Achievements & Impact" },
  { value: "potential_red_flags", label: "Potential Red Flags" },
  {
    value: "cultural_fit_and_adaptability",
    label: "Cultural Fit & Adaptability",
  },
];

export const FeedbackFilterOption = [
  { value: "GIVEN", label: "Given" },
  { value: "NOT_GIVEN", label: "Not Given" },
];

export const MailFilterOption = [
  { value: "SENT", label: "Sent" },
  { value: "NOT_SENT", label: "Not Sent" },
];

export const AssignTaskFilterOption = [
  { value: "ASSIGNED", label: "Assigned" },
  { value: "NOT_ASSIGNED", label: "Not Assigned" },
];

export const ResultFilterOption = [
  { value: "PASSED", label: "Passed" },
  { value: "FAILED", label: "Failed" },
];

export const sortOldNewData = [
  {
    level: "Newest First",
    sort_by: "start_at",
    sort_order: "desc",
  },
  {
    level: "Oldest First",
    sort_by: "start_at",
    sort_order: "asc",
  },
];

export const sortYearMonthWeekData = [
  { label: "This Year", value: "year" },
  { label: "This Month", value: "month" },
  { label: "This Week", value: "week" },
];

export const lightToolTipTheme = {
  tooltip: {
    sx: {
      backgroundColor: "#fff",
      color: "#454545",
      border: "1px solid #e7e7e7",
      boxShadow: "0px 2px 4px rgba(0, 0, 0, 0.1)",
      fontSize: "13px",
      fontWeight: 400,
    },
  },
};

export const darkToolTipTheme = {
  tooltip: {
    sx: {
      backgroundColor: "#333",
      color: "#fff",
      border: "1px solid #444",
      boxShadow: "0px 2px 4px rgba(0, 0, 0, 0.2)",
      fontSize: "13px",
      fontWeight: 400,
    },
  },
};